[project]
name = "coeiroink-dockerfile"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "json5>=0.12.0",
    "requests>=2.32.3",
]
